export default {
    products: [
        {
        _id: '1',
        name: 'Pastel 3 leches',
        category: 'Cakes',
        image: '/images/cake.png',
        price:60,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '2',
        name: 'Pastel 3 leches',
        category: 'Cakes',
        image: '/images/cake4.png',
        price:30,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
        countInStock: 0,
    },
    {
        _id: '3',
        name: 'Pastel 3 leches',
        category: 'Cakes',
        image: '/images/cake5.png',
        price:50,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '4',
        name: 'Pastel 3 leches',
        category: 'Cakes',
        image: '/images/cake3.png',
        price:50,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '5',
        name: 'Pastel 3 leches',
        category: 'Cakes',
        image: '/images/cake4.png',
        price:50,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '6',
        name: 'Pastel 3 leches',
        category: 'Cakes',
        image: '/images/cake5.png',
        price:50,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '7',
        name: 'Pastel 3 leches',
        category: 'Cakes',
        image: '/images/cake6.png',
        price:50,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '8',
        name: 'Pastel 3 leches',
        category: 'Cakes',
        image: '/images/cake2.png',
        price:50,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
]
}