export default {
    products: [
        {
        _id: '1',
        name: 'cake 3 milks',
        category: 'Cakes',
        image: '/images/cake.png',
        price:60,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
    },
    {
        _id: '2',
        name: 'cake 2 milks',
        category: 'Cakes',
        image: '/images/cake.png',
        price:30,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
    },
    {
        _id: '3',
        name: 'cake 3 milks',
        category: 'Cakes',
        image: '/images/cake.png',
        price:50,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
    },
    {
        _id: '4',
        name: 'cake 3 milks',
        category: 'Cakes',
        image: '/images/cake.png',
        price:50,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
    },
    {
        _id: '5',
        name: 'cake 3 milks',
        category: 'Cakes',
        image: '/images/cake.png',
        price:50,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
    },
    {
        _id: '6',
        name: 'cake 3 milks',
        category: 'Cakes',
        image: '/images/cake.png',
        price:50,
        brand: 'Chocolate',
        rating: 4.5,
        numReviews: 10,
    },
]
}